System OPL/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using DotNetOpenAuth.AspNet.Clients;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using System_OPL.Models;
using System_OPL.Controllers;
using System.ComponentModel.DataAnnotations;


namespace System_OPL
{
    public class PatientController : BaseController
    {
        //
        // GET: /Patient/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Account/Register

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Patient model)
        {
            if (ModelState.IsValid)
            {                
                try
                {
                    var doctor = context.Doctors.FirstOrDefault(x => x.UserName == WebSecurity.CurrentUserName);
                    model.DoctorId=doctor.Id;
                    context.Patients.Add(model);
                    context.SaveChanges();                   
                    return RedirectToAction("Index", "Home");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("","Rejestracja Pacjentki nie powiodła się.");
                }
            }
            
            return View(model);
        }

        [Authorize]
        public ActionResult List()
        {
            IQueryable<Patient> patients;
            //if (Roles.IsUserInRole("Ordynator"))
            //{
            //    patients = context.Patients;
            //}
            //else
            //{
            //    var userId = WebSecurity.GetUserId(User.Identity.Name);
            //    patients = context.Patients.Where(x => x.DoctorId == userId);
            //}

            patients = context.Patients;

            return View(patients);
        }

        public ViewResult FakerCreate()
        {
            var amount = new FakerAmountViewModel();

            return View(amount);
        }

        [HttpPost]
        public ActionResult FakerCreate(FakerAmountViewModel faker)
        {
            if (ModelState.IsValid)
            {
                var clientRepo = new PatientRepository();
                clientRepo.ClientFakerInsert(faker.Amount);

                return RedirectToAction("List");
            }

            ModelState.AddModelError(null, "Podaj właściwą liczbę rekordów");
            return View(faker);

        }
            

    }
}

System OPL/Controllers/SupplyController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using DotNetOpenAuth.AspNet.Clients;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using System_OPL.Models;
using System_OPL.Controllers;
using System.ComponentModel.DataAnnotations;

namespace System_OPL
{
    public class SupplyController : BaseController
    {
        //
        // GET: /Supply/

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult List()
        {
              IQueryable<Supply> supplies;
              supplies = context.Supplies;    
              return View(supplies);
        }

    }
}

System OPL/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System_OPL.Models;

namespace System_OPL.Controllers
{
    public class TestController : BaseController
    {

        //
        // GET: /Test/

        public ActionResult Index()
        {
            var tests = context.Tests.Include(t => t.Object).Include(t => t.Doctors).Include(t => t.Nurses);
            return View(tests.ToList());
        }


        public ActionResult Create()
        {
            ViewBag.ObjectId = new SelectList(context.Patients, "Id", "Name");
            ViewBag.DoctorId = new SelectList(context.Doctors, "Id", "UserName");
            ViewBag.NurseId = new SelectList(context.Nurses, "Id", "UserName");
            return View();
        }



        [HttpPost]
        public ActionResult Create(Test test)
        {
            if (ModelState.IsValid)
            {
                context.Tests.Add(test);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ObjectId = new SelectList(context.Patients, "Id", "Name", test.ObjectId);
            ViewBag.DoctorId = new SelectList(context.Doctors, "Id", "UserName", test.DoctorId);
            ViewBag.NurseId = new SelectList(context.Nurses, "Id", "UserName", test.NurseId);
            return View(test);
        }



        public ActionResult Edit(int id = 0)
        {
            Test test = context.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            ViewBag.ObjectId = new SelectList(context.Patients, "Id", "Name", test.ObjectId);
            ViewBag.DoctorId = new SelectList(context.Doctors, "Id", "UserName", test.DoctorId);
            ViewBag.NurseId = new SelectList(context.Nurses, "Id", "UserName", test.NurseId);
            return View(test);
        }

        [HttpPost]
        public ActionResult Edit(Test test)
        {
            if (ModelState.IsValid)
            {
                context.Entry(test).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ObjectId = new SelectList(context.Patients, "Id", "Name", test.ObjectId);
            ViewBag.DoctorId = new SelectList(context.Doctors, "Id", "UserName", test.DoctorId);
            ViewBag.NurseId = new SelectList(context.Nurses, "Id", "UserName", test.NurseId);
            return View(test);
        }

        public ActionResult Delete(int id = 0)
        {
            Test test = context.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Test test = context.Tests.Find(id);
            context.Tests.Remove(test);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
            base.Dispose(disposing);
        }
    }
}

System OPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>      
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("OPL - System Organizacji czasu Pracy Lekarzy", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    @if (User.IsInRole("Doctor") || User.IsInRole("Ordynator"))
                    { 
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Pacjenci", "List", "Patient")</li>
                            @*<a href="~/Views/Shared/_Layout.cshtml">~/Views/Shared/_Layout.cshtml</a>*@
                            <li>@Html.ActionLink("Zadania", "Index", "Test")</li>
                            <li>@Html.ActionLink("Zasoby", "List", "Supply")</li>
                            <li>@Html.ActionLink("Baza danych","FakerCreate","Patient" )</li>                           
                        </ul>
                    </nav>
                    }
                    @if (User.IsInRole("Nurse"))
                    {
                    }
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
            @if(!Request.IsAuthenticated)
            {
                <div style="padding-left: 35%; width:60%">
                  <div style="position:center"> 
                     <span style="font-size: 40px">@DateTime.Now.Day-@DateTime.Now.Month-@DateTime.Now.Year </span><br />
                     <span style="font-size: 40px">@DateTime.Now.DayOfWeek </span><br /><br />
                      <span style="font-size: 20px">Witaj. Proszę się zalogować.</span>
                      
                  </div>
                </div>
            }
            else
            {
                <div style="padding-left: 35%; width:60%">
                    <div style="position:center">
                        <br /><br />
                        <br /><br />
                        <span style="font-size: 15px">@DateTime.Now.Day-@DateTime.Now.Month-@DateTime.Now.Year @DateTime.Now.DayOfWeek </span><br />                        
                        <div>
                            <img alt="" src="Images/Logo.jpg"/>
                        </div>                        
                    </div>
                </div>

            }
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>                    
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>